apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f65swodzr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f65swodzr-nodejs 
  name: f65swodzr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: f65swodzr-nodejs 
